### ISSUE TITLE
Check Network Time Error

### ISSUE THREAD

**Issue by cyb3rr0nn13** [adafruit/Adafruit_FONA#123]
Hi....
i bought a [thingsmobile SIM](https://www.thingsmobile.com/), and a [WHiD-31337](https://github.com/whid-injector/whid-31337).

When I installed everything with the [Arduino IDE](https://arduino.cc) so far and 
tried to address the FONA SIM800l via AT Serial Monitor, 
i received the following error message:

23:58:23.583 -> FONA basic test
23:58:23.583 -> Initializing....(May take 3 seconds)
23:58:23.682 -> Attempting to open comm with ATs
23:58:23.754 -> 	---> AT
23:58:23.754 -> 	<--- AT
23:58:23.798 -> 	---> AT
23:58:23.798 -> 	<--- AT
23:58:23.855 -> 	---> ATE0
23:58:23.916 -> 	<--- ATE0
23:58:24.008 -> 	---> ATE0
23:58:24.008 -> 	<--- OK
23:58:24.105 -> 	---> AT+CVHU=0
23:58:24.105 -> 	<--- OK
23:58:24.227 -> 	---> ATI
23:58:24.720 -> 	<--- SIM800 R14.18
23:58:24.720 -> 
23:58:24.720 -> OK
23:58:24.720 -> 
23:58:24.800 -> 	---> AT+CPMS="SM","SM","SM"
23:58:24.886 -> 	<--- +CPMS: 0,10,0,10,0,10
23:58:24.886 -> FONA is OK
23:58:24.886 -> Found ???
23:58:25.075 -> 
23:58:25.075 -> FONA> t
00:00:22.660 -> 	---> AT+CCLK?
00:00:32.813 -> 	<--- 
00:00:32.813 -> Time = ⸮⸮⸮R⸮4⸮⸮RL⸮⸮⸮Թ⸮⸮⸮>⸮dy
00:00:32.813 -> ⸮2⸮!⸮⸮xrE⸮⸮⸮3C⸮!⸮O⸮y⸮⸮⸮t⸮⸮⸮
00:00:32.813 -> Q⸮
00:00:32.813 -> ιC⸮⸮zȀ⸮⸮Q⸮⸮⸮⸮#r⸮!⸮⸮A⸮,z⸮⸮⸮8-⸮⸮;⸮&,⸮pp⸮⸮⸮⸮dY⸮⸮и)⸮⸮s⸮⸮S⸮⸮
00:00:32.813 -> y
00:00:32.813 -> FONA>

WTF ?! 
What's that? 
And does anyone know how to fix that? 
Thank you very much!

**Comment by ladyada** [comment]
hi please start by contacting WHiD for tech support if you purchased their product, they will be able to help you with technical assistance :)
