### ISSUE TITLE
Pass variable to send SMS

### ISSUE THREAD

**Issue by mohammadbax98** [adafruit/Adafruit_FONA#127]
Hello.
For examples, you use this code: fona.sendSMS(callerIDbuffer, "Hey, I got your text!")
But I can't pass any variable.
I get "no matching function for call to 'Adafruit_FONA::sendSMS(char [32], String)'"
I test this simple code and it does not work!

String test = "Hey, I got your text!";
fona.sendSMS(callerIDbuffer, test)

I want to pass for example my sensor humidity and temperature. how can I fix this problem?

**Comment by ladyada** [comment]
use sprintf or some other way to generate a string. check arduino forums for support.
