### ISSUE TITLE
Buzzing with the FONA

### ISSUE THREAD

**Issue by maurbeck** [adafruit/Adafruit_FONA#54]
Can we update the function for setting the PWM of the buzzer? The Feather FONA doesn't have a dedicated PWM pin for the buzzer so it'd be nice to be able to set a pin for this for Feather FONA use.

**Comment by ladyada** [comment]
doesnt work that way, you have to do it thru the Arduino IDE - the FONA library wouldnt make sense. try Tone() or analogWrite()!

**Comment by maurbeck** [comment]
Ok, thanks. DUH! I was approaching it entirely the wrong way...
