### ISSUE TITLE
ADAFRUIT_FONA_DEBUG now set by default?

### ISSUE THREAD

**Issue by markusk** [adafruit/Adafruit_FONA#63]
Was this define set purposely or by coincidence?
File: includes/FONAConfig.h

I just updated this library via Arduino GUI and got all the debug messages....

**Comment by ladyada** [comment]
yes

**Comment by kevinjwalters** [comment]
How would an Arduino sketch disable this?

It looks like this is triggered by `#define ADAFRUIT_FONA_DEBUG` in https://github.com/adafruit/Adafruit_FONA/blob/eeec7015b2e2060fdfdc416eb758452dcfd00308/includes/FONAConfig.h#L31 and user code gets that indirectly from doing `#include "Adafruit_FONA.h"`.

**Comment by ladyada** [comment]
you have to comment out that line to disable it
