### ISSUE TITLE
GPS Data did not get in the indoor location/environment 

### ISSUE THREAD

**Issue by Bhavikjp** [adafruit/Adafruit_FONA#95]
GPS Data did not get to the indoor location. I have used SIM808 EVB-v 3.2.2 GSM/GPRS + GPS board.

It has the functionality to receive GPS data and **A-GPS data**.

I have used the same Adafruit_FONA Library.

**How to get GPS response in the indoor location?
How to access A-GPS?**

I did not get GPS data in the indoor location. "I got data outside in the open air environment."

Can you please suggest me to get GPS data in the indoor environment.

**Thanks!!**

**Comment by ladyada** [comment]
you cannot get GPS indoors, its outdoors only!
